# Generated by Django 3.1.1 on 2020-10-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('upload_date', models.CharField(max_length=10)),
                ('user', models.CharField(max_length=200)),
                ('captions', models.TextField(null=True)),
                ('thumbnail_url', models.TextField()),
                ('video_url', models.TextField()),
                ('length', models.CharField(max_length=200)),
                ('views', models.CharField(max_length=200)),
            ],
        ),
    ]
