# Generated by Django 3.1.1 on 2020-10-09 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201007_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.CharField(default='text', max_length=200),
        ),
    ]
