# Generated by Django 3.1.2 on 2020-10-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_object_videoobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='videos',
            field=models.ManyToManyField(to='search.Video'),
        ),
        migrations.DeleteModel(
            name='VideoObject',
        ),
    ]
